In [1]:
import numpy as np
import cv2
import os
import math
import matplotlib.pyplot as plt

In [152]:
'''
    For Code Testing 
'''

#Line = np.array([[0,2,3],[0,5,6],[0,7,8]])

#Line = np.sum(Line,axis=0)
print(Line)

#VP = [ int(np.sum(Line[:,j] ) == 0)  for j in range( len(Line[0]) ) ]

#print(VP)

#G = np.array([1,2,3,4,5,6,7,8,9])
#G = G[ G < 5 ]
#print(G)

[[0 2 3]
 [0 5 6]
 [0 7 8]]


In [153]:
# Gaps are whether Gaps between words OR Gaps within sub-word
# removing sub-word Gaps
def FilterGaps(G,L):
    
    G = np.array(G)
    L = np.array(L)
    
    IQR = 2
    
    # Filtering Depending On IQR ( Interquartile Range ) Value
    G = G[ L >= IQR ]
    L = L[ L >= IQR ]
    
    Mean = np.mean(L)
    G = G[ L >= Mean ]
    L = L[ L >= Mean ]
    
    
    return G,L

In [154]:
def FindGaps(Line):
    
    G = []
    L = []

    # Vertical Projection Of the text
    VP = np.sum(Line,axis=0)    
    flag = 0
    for i in range(len(VP)):
        
        if VP[i] == 0 :
            if flag == 0:
                # This is a Gap Start 
                G.append(i)
                L.append(1)
                flag = 1
            else:
                # Increment Gap Length
                L[-1] +=1
            
        
        elif flag == 1:
            # End of The Gap
            flag = 0
        
    
    return G,L

In [155]:
def WordSegment(Line):
    
    # G => Array of Gaps, L => Length of each gap
    G,L = FindingGaps(Line)
    G,L = FilterGaps(G,L)
    
    # Separete Each Word in a single Image
    Words = [ Line[0:,G[i]+L[i]:G[i+1]] for i in range(len(G)-1) ]    
    
    return Words

In [156]:
def ToBinaryImg(Img):
    ImgGray = cv2.cvtColor(Img, cv2.COLOR_BGR2GRAY)
    BinaryImg = np.array(ImgGray)
    BinaryImg[ ImgGray > 127 ] = 0
    BinaryImg[ ImgGray <= 127 ] = 255
    
    return BinaryImg

In [157]:
Img = cv2.imread('2.png')
BinaryImg = ToBinaryImg(Img)

# Segment Words
Words = WordSegment(BinaryImg)


#for i in range(len(G)):
#    Img= cv2.rectangle(Img, (G[1]+L[1]-5,0), (G[1]+L[1]-5,dim[1]), (0,255,0), 2)

for x in Words[::-1]:
    cv2.imshow('Test Image',x)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
#print(blackAndWhiteImage)
